theme: jekyll-theme-minimal
title: Welcome to Construct Digital's Homepage
description: We are a digital marketing agency that can design, build, market and optimise your website
logo: Construct_Logo_ForWeb_600x250px.png
