theme: jekyll-theme-minimal
title: Welcome to Construct Analytics's Homepage
description: Part of Construct Digital! Everything about Data Analysis (almost).
logo: Construct_Logo_ForWeb_600x250px.png
